# Generated by Django 2.1.7 on 2019-03-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video1', to='lesson.Videos'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video2', to='lesson.Videos'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video3', to='lesson.Videos'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video4', to='lesson.Videos'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video5', to='lesson.Videos'),
        ),
    ]
