# Generated by Django 2.1.7 on 2019-03-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video1', to='lesson.Videos'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video2', to='lesson.Videos'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video3', to='lesson.Videos'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video4', to='lesson.Videos'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video5', to='lesson.Videos'),
        ),
    ]
