# Generated by Django 2.1.7 on 2019-03-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20190325_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_2',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_3',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_4',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video_5',
        ),
        migrations.AddField(
            model_name='videos',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lesson.Lessons'),
        ),
    ]
