# Generated by Django 2.1.7 on 2019-03-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20190325_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='videos',
        ),
        migrations.AddField(
            model_name='videos',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lesson.Lessons'),
        ),
    ]
