# Generated by Django 2.1.7 on 2019-03-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lessons_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='play',
        ),
        migrations.AddField(
            model_name='videos',
            name='play',
            field=models.BooleanField(default=False),
        ),
    ]
