# Generated by Django 2.1.7 on 2019-04-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20190404_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='number',
            field=models.IntegerField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
