# Generated by Django 2.1.7 on 2019-04-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_lessons_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='description',
            field=models.CharField(blank=True, max_length=8008, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=8008, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=8008, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='number',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='number',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
