# Generated by Django 2.1.7 on 2019-04-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_auto_20190405_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
    ]
