# Generated by Django 2.1.7 on 2019-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_auto_20190425_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='stopped',
            field=models.BooleanField(default=True),
        ),
    ]
